// This file was generated by counterfeiter
package authfakes

import (
	"sync"

	"github.com/sgravrock/flickr-to-go-go/auth"
)

type FakeOauthClient struct {
	NewConsumerStub        func(key string, secret string, requestTokenUrl string, authorizeTokenUrl string, accessTokenUrl string) auth.OauthConsumer
	newConsumerMutex       sync.RWMutex
	newConsumerArgsForCall []struct {
		key               string
		secret            string
		requestTokenUrl   string
		authorizeTokenUrl string
		accessTokenUrl    string
	}
	newConsumerReturns struct {
		result1 auth.OauthConsumer
	}
}

func (fake *FakeOauthClient) NewConsumer(key string, secret string, requestTokenUrl string, authorizeTokenUrl string, accessTokenUrl string) auth.OauthConsumer {
	fake.newConsumerMutex.Lock()
	fake.newConsumerArgsForCall = append(fake.newConsumerArgsForCall, struct {
		key               string
		secret            string
		requestTokenUrl   string
		authorizeTokenUrl string
		accessTokenUrl    string
	}{key, secret, requestTokenUrl, authorizeTokenUrl, accessTokenUrl})
	fake.newConsumerMutex.Unlock()
	if fake.NewConsumerStub != nil {
		return fake.NewConsumerStub(key, secret, requestTokenUrl, authorizeTokenUrl, accessTokenUrl)
	} else {
		return fake.newConsumerReturns.result1
	}
}

func (fake *FakeOauthClient) NewConsumerCallCount() int {
	fake.newConsumerMutex.RLock()
	defer fake.newConsumerMutex.RUnlock()
	return len(fake.newConsumerArgsForCall)
}

func (fake *FakeOauthClient) NewConsumerArgsForCall(i int) (string, string, string, string, string) {
	fake.newConsumerMutex.RLock()
	defer fake.newConsumerMutex.RUnlock()
	return fake.newConsumerArgsForCall[i].key, fake.newConsumerArgsForCall[i].secret, fake.newConsumerArgsForCall[i].requestTokenUrl, fake.newConsumerArgsForCall[i].authorizeTokenUrl, fake.newConsumerArgsForCall[i].accessTokenUrl
}

func (fake *FakeOauthClient) NewConsumerReturns(result1 auth.OauthConsumer) {
	fake.NewConsumerStub = nil
	fake.newConsumerReturns = struct {
		result1 auth.OauthConsumer
	}{result1}
}

var _ auth.OauthClient = new(FakeOauthClient)
