// This file was generated by counterfeiter
package dlfakes

import (
	"sync"

	"github.com/sgravrock/flickr-to-go-go/dl"
	"github.com/sgravrock/flickr-to-go-go/flickrapi"
)

type FakeDownloader struct {
	DownloadPhotolistStub        func(flickr flickrapi.Client) ([]flickrapi.PhotoInfo, error)
	downloadPhotolistMutex       sync.RWMutex
	downloadPhotolistArgsForCall []struct {
		flickr flickrapi.Client
	}
	downloadPhotolistReturns struct {
		result1 []flickrapi.PhotoInfo
		result2 error
	}
}

func (fake *FakeDownloader) DownloadPhotolist(flickr flickrapi.Client) ([]flickrapi.PhotoInfo, error) {
	fake.downloadPhotolistMutex.Lock()
	fake.downloadPhotolistArgsForCall = append(fake.downloadPhotolistArgsForCall, struct {
		flickr flickrapi.Client
	}{flickr})
	fake.downloadPhotolistMutex.Unlock()
	if fake.DownloadPhotolistStub != nil {
		return fake.DownloadPhotolistStub(flickr)
	} else {
		return fake.downloadPhotolistReturns.result1, fake.downloadPhotolistReturns.result2
	}
}

func (fake *FakeDownloader) DownloadPhotolistCallCount() int {
	fake.downloadPhotolistMutex.RLock()
	defer fake.downloadPhotolistMutex.RUnlock()
	return len(fake.downloadPhotolistArgsForCall)
}

func (fake *FakeDownloader) DownloadPhotolistArgsForCall(i int) flickrapi.Client {
	fake.downloadPhotolistMutex.RLock()
	defer fake.downloadPhotolistMutex.RUnlock()
	return fake.downloadPhotolistArgsForCall[i].flickr
}

func (fake *FakeDownloader) DownloadPhotolistReturns(result1 []flickrapi.PhotoInfo, result2 error) {
	fake.DownloadPhotolistStub = nil
	fake.downloadPhotolistReturns = struct {
		result1 []flickrapi.PhotoInfo
		result2 error
	}{result1, result2}
}

var _ dl.Downloader = new(FakeDownloader)
